spring:
    datasource:
        url: jdbc:postgresql://SvNk9MYjR8LnivPDmavzUrD1cttiyDLU@dpg-cibrq6l9aq03rjh0jsd0-a.oregon-postgres.render.com:5432/midefensadatabase
        username: midefensadatabase_user
        password: SvNk9MYjR8LnivPDmavzUrD1cttiyDLU
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000
            refresh-token:
                expiration: 604800000
server:
    port: 8080